### ISSUE TITLE
Waiting to send out remaining messages always runs into timeout after SW update

### ISSUE THREAD

**Issue by patrickjaigner** [tum-esm/hermes#131]
Perform update
function to waiting to send out remaining messages always runs into its 2 minute timeout.

TODO: Root Cause Analysis

**Comment by larsfroelich** [comment]
I investigated this and found out that it is due to one message being left in the DB (but which doesn't have the "in-progress" value).
I have fixed this bug by simply waiting for the nr of "in-progress" msgs to drop to 0, rather than the nr of all messages in the db

**Comment by patrickjaigner** [comment]
Will be merged and tested here: https://github.com/tum-esm/ACROPOLIS-edge/pull/11
