### ISSUE TITLE
Concept for shutdown routine on low battery

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/hermes#33]
- [ ] Do not do config upgrades on low battery power
- [ ] Do not perform calibration procedures on low batter power
- [ ] Shut down energy intensive hardware components (wind sensor, etc.?)

**Comment by patrickjaigner** [comment]
Currently, UPS is set up with 1h runtime instead of an infinite runtime. 
It's not in scope anymore -> CWA
