### ISSUE TITLE
Perform quick hard reset once, when CO2 sensor sends "unknown command" error

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/hermes#59]
The $CO_2$ sensor regularly has an outage of not being able to process a command. This will result in a full teardown routine and regular log messages due to a known issue that we cannot get rid of:

![sensor_activity_8](https://user-images.githubusercontent.com/29046316/224495443-3cd757aa-ecb8-4af3-a87c-78dedf4b544d.png)

We should add a single retry inside the $CO_2$ sensors class so that these warnings will only be sent, when the error happens more than once in 30 minutes, for example.

**Comment by patrickjaigner** [comment]
Fixed with 0.2.0-beta.1
