### ISSUE TITLE
Use Pydantic's JSON schema to validate the config in the dashboard

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/hermes#85]
Pydantic can generate a JSON Schema for validation that complies with the JSON Schema of https://json-schema.org/: https://docs.pydantic.dev/latest/usage/schema/

We can use that JSON for every published release to validate new configs in the frontend using a library like https://ajv.js.org/.

I think the best idea to "publish" this schema definition is to attach it to releases as JSON files and let the dashboard grab those files at runtime.

**Comment by patrickjaigner** [comment]
Dashboard is developed further in different repository.
