### ISSUE TITLE
Missing in-flow data during calibration

### ISSUE THREAD

**Issue by patrickjaigner** [tum-esm/hermes#87]
There is no in-flow sensor data being communicated during calibration.

EDIT: There is also no logging locally. 

Some examples plotted from the database:
![Humidity_sht45](https://github.com/tum-esm/hermes/assets/59452158/4bffa12f-ce16-451b-b3ee-d829c16bec62)
![Pressure_bme280](https://github.com/tum-esm/hermes/assets/59452158/5727f02b-1044-4456-919e-ddc247a98ebc)

**Comment by dostuffthatmatters** [comment]
No, the data is not logged locally. This data is only logged every measurement iteration during regular measurements.

**Comment by patrickjaigner** [comment]
There is a high priority to have this data for proper analysis during calibration and system analysis.

**Comment by patrickjaigner** [comment]
Merged in https://github.com/tum-esm/hermes/pull/101
