### ISSUE TITLE
Dashboard components: add activity chart

### ISSUE THREAD

**Issue by empicano** [tum-esm/hermes#9]
What do you think about adding an activity chart, showing sensor activity over the last month or so? I implemented this for the AQSN project, like so:

<img width="1042" alt="Screenshot 2022-10-30 at 20 39 56" src="https://user-images.githubusercontent.com/26978146/198898295-fcc0742a-3269-402a-9625-aa0f4bc76445.png">

If there's interest, I'll implement a similar query here and return the activity data together with the sensor configurations on the `GET /sensors` route.

The dashboard can follow whenever, I'm only asking because it would fit well for me atm.

**Comment by dostuffthatmatters** [comment]
I would like to add this :) which HTTP route should I use to get the aggregated heartbeats. Very low priority, though.

**Comment by patrickjaigner** [comment]
Dashboard is developed further in different repository.
