### ISSUE TITLE
Server not receiving all log messages?

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/hermes#90]
If you look at the aggregated logs of sensor 1, the last log message (except heartbeats) is 45 days old:

<img width="500" alt="Screenshot 2023-06-07 at 12 57 09" src="https://github.com/tum-esm/hermes/assets/29046316/a89fdd26-1e02-42ef-8e85-479ea9fad938">

There are significantly newer log messages than that. @empicano could you check, whether more log messages have arrived since then?

**Comment by dostuffthatmatters** [comment]
> I can't find newer logs in the database. Locally, receiving logs works fine and I don't see any errors in the server logs either.

Weird.

> Is there a sensor actively sending logs at the moment so that we can test this?

We can test this during the Friday meeting.

**Comment by patrickjaigner** [comment]
Root cause: MQTT topics on the system and server where slightly different.
