### ISSUE TITLE
Sensor Teardown kills LTE Antenna connection

### ISSUE THREAD

**Issue by patrickjaigner** [tum-esm/hermes#92]
After a reboot with deactivated crontab -e commands the LTE antenna connection is working as expected.
After starting the sensor automation with hermes-cli start the antenna connection dies.

Solution:
Resend the two commands after teardown:
sudo /home/pi/SIM8200_for_RPI/Goonline/simcom-cm &
sudo udhcpc -i wwan0

pi@tum-esm-midcost-raspi-10:~ $ ping -I wwan0 www.google.de
PING  (142.251.36.163) from 10.179.201.108 wwan0: 56(84) bytes of data.
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=1 ttl=111 time=68.1 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=2 ttl=111 time=86.4 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=3 ttl=111 time=94.9 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=4 ttl=111 time=86.2 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=5 ttl=111 time=93.0 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=6 ttl=111 time=92.8 ms
^C
---  ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5004ms
rtt min/avg/max/mdev = 68.056/86.907/94.923/9.059 ms
pi@tum-esm-midcost-raspi-10:~ $ hermes-cli
Usage: hermes-cli [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  enclosure   Manage the enclosure arduino board
  info        Information about which CLI version and path is used
  is-running  Checks whether the background processes are running
  restart     Stop and start the automation as a background process.
  start       Start the automation as a background process.
  stop        Stop the automation's background process
pi@tum-esm-midcost-raspi-10:~ $ hermes-cli start
nohup: appending output to 'nohup.out'
Started background process with PID(s) [2373]
pi@tum-esm-midcost-raspi-10:~ $ ping -I wwan0 www.google.de
PING  (142.251.36.163) from 10.179.201.108 wwan0: 56(84) bytes of data.
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=1 ttl=111 time=78.6 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=2 ttl=111 time=75.8 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=3 ttl=111 time=93.7 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=4 ttl=111 time=83.6 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=5 ttl=111 time=80.9 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=6 ttl=111 time=80.0 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=7 ttl=111 time=80.0 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=8 ttl=111 time=79.0 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=9 ttl=111 time=78.0 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=10 ttl=111 time=77.0 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=11 ttl=111 time=94.0 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=12 ttl=111 time=92.7 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=13 ttl=111 time=83.2 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=14 ttl=111 time=81.5 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=15 ttl=111 time=86.7 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=16 ttl=111 time=85.7 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=17 ttl=111 time=85.3 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=18 ttl=111 time=92.3 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=19 ttl=111 time=84.6 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=20 ttl=111 time=83.1 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=21 ttl=111 time=83.1 ms
^C
---  ping statistics ---
117 packets transmitted, 21 received, 82.0513% packet loss, time 118304ms
rtt min/avg/max/mdev = 75.819/83.760/94.041/5.372 ms
pi@tum-esm-midcost-raspi-10:~ $ ping -I wwan0 www.google.de
PING  (142.250.186.99) from 169.254.7.254 wwan0: 56(84) bytes of data.
From tum-esm-midcost-raspi-10.local (169.254.7.254) icmp_seq=1 Destination Host Unreachable
From tum-esm-midcost-raspi-10.local (169.254.7.254) icmp_seq=2 Destination Host Unreachable
From tum-esm-midcost-raspi-10.local (169.254.7.254) icmp_seq=3 Destination Host Unreachable
From tum-esm-midcost-raspi-10.local (169.254.7.254) icmp_seq=4 Destination Host Unreachable
^C
---  ping statistics ---
7 packets transmitted, 0 received, +4 errors, 100% packet loss, time 6148ms
pipe 4
pi@tum-esm-midcost-raspi-10:~ $ sudo /home/pi/SIM8200_for_RPI/Goonline/simcom-cm &
[1] 2804
pi@tum-esm-midcost-raspi-10:~ $ [06-15_16:10:11:210] Build Version: 2020-07-14 10:20:15
[06-15_16:10:11:210] SIMCOM_CM START...
[06-15_16:10:11:210] /home/pi/SIM8200_for_RPI/Goonline/simcom-cm profile[1] = (null)/(null)/(null)/0, pincode = (null)
[06-15_16:10:11:212] Find /sys/bus/usb/devices/1-1.4 idVendor=1e0e idProduct=9001
[06-15_16:10:11:212] Find /sys/bus/usb/devices/1-1.4:1.5/net/wwan0
[06-15_16:10:11:212] Find usbnet_adapter = wwan0
[06-15_16:10:11:212] Find /sys/bus/usb/devices/1-1.4:1.5/usbmisc/cdc-wdm0
[06-15_16:10:11:212] Find qmichannel = /dev/cdc-wdm0
[06-15_16:10:11:213] netcard driver = qmi_wwan
[06-15_16:10:11:228] /proc/679/fd/7 -> /dev/cdc-wdm0
[06-15_16:10:11:228] /proc/679/exe -> /usr/libexec/qmi-proxy
[06-15_16:10:13:250] cdc_wdm_fd = 7
[06-15_16:10:13:349] Get clientWDS = 17
[06-15_16:10:13:381] Get clientDMS = 1
[06-15_16:10:13:413] Get clientNAS = 1
[06-15_16:10:13:445] Get clientUIM = 1
[06-15_16:10:13:477] Get clientWDA = 1
[06-15_16:10:13:509] requestBaseBandVersion LE20B04SIM7600M22
[06-15_16:10:13:573] requestGetSIMStatus SIMStatus: SIM_READY
[06-15_16:10:13:605] requestGetProfile[1] iotde.telefonica.com///0
[06-15_16:10:13:637] requestRegistrationState2 MCC: 262, MNC: 1, PS: Attached, DataCap: LTE
[06-15_16:10:13:669] requestQueryDataCall IPv4ConnectionStatus: DISCONNECTED
[06-15_16:10:13:733] requestRegistrationState2 MCC: 262, MNC: 1, PS: Attached, DataCap: LTE
[06-15_16:10:13:765] requestSetupDataCall WdsConnectionIPv4Handle: 0x86f5b730
[06-15_16:10:13:829] requestQueryDataCall IPv4ConnectionStatus: CONNECTED
[06-15_16:10:13:861] ifconfig wwan0 up
[06-15_16:10:13:869] Fail to access /usr/share/udhcpc/default.script, errno: 2 (No such file or directory)
[06-15_16:10:13:869] ifconfig wwan0 down
[06-15_16:10:13:883] echo Y > /sys/class/net/wwan0/qmi/raw_ip
[06-15_16:10:13:884] ifconfig wwan0 up
[06-15_16:10:13:896] busybox udhcpc -f -n -q -t 5 -s /usr/share/udhcpc/default.script -i wwan0
udhcpc: started, v1.30.1
udhcpc: sending discover
udhcpc: sending select for 10.179.201.108
udhcpc: lease of 10.179.201.108 obtained, lease time 7200
^C
pi@tum-esm-midcost-raspi-10:~ $ ping -I wwan0 www.google.de
ping: Warning: source address might be selected on device other than: wwan0
PING  (142.250.186.99) from 192.168.161.72 wwan0: 56(84) bytes of data.
^C
---  ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4088ms

pi@tum-esm-midcost-raspi-10:~ $ sudo udhcpc -i wwan0
udhcpc: started, v1.30.1
udhcpc: sending discover
udhcpc: sending select for 10.179.201.108
udhcpc: lease of 10.179.201.108 obtained, lease time 7200
pi@tum-esm-midcost-raspi-10:~ $ ping -I wwan0 www.google.de
PING  (142.251.36.163) from 10.179.201.108 wwan0: 56(84) bytes of data.
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=1 ttl=111 time=72.7 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=2 ttl=111 time=80.8 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=3 ttl=111 time=78.0 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=4 ttl=111 time=85.9 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=5 ttl=111 time=86.9 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=6 ttl=111 time=93.9 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=7 ttl=111 time=92.9 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=8 ttl=111 time=83.0 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=9 ttl=111 time=83.0 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=10 ttl=111 time=89.8 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=11 ttl=111 time=79.8 ms
64 bytes from 142.251.36.163 (142.251.36.163): icmp_seq=12 ttl=111 time=80.4 ms
^C
---  ping statistics ---
12 packets transmitted, 12 received, 0% packet loss, time 11012ms
rtt min/avg/max/mdev = 72.722/83.932/93.922/5.984 ms

**Comment by dostuffthatmatters** [comment]
The interface to the heated enclosure is regularly powering down and up all USB ports because the connection to the Arduino is so terrible. It writes that "USB toggling" in the logs too. Might be the reason for the interference.

**Comment by patrickjaigner** [comment]
I removed the serial communication from the Arduino in 0.2.0.beta-1. The Arduino is currently flashed via Laptop instead of the Raspberry Pi. All systems have the heated-enclosure thread deactivated in the config.
